DROP TABLE IF EXISTS SINGER;
DROP SEQUENCE IF EXISTS global_seq;
CREATE SEQUENCE global_seq START WITH 1;

CREATE TABLE SINGER
(
    ID          INT NOT NULL PRIMARY KEY DEFAULT nextval('global_seq'),
    FIRST_NAME  VARCHAR(60) NOT NULL,
    LAST_NAME   VARCHAR(40) NOT NULL,
    BIRTH_DATE  DATE,
    DESCRIPTION VARCHAR(2000),
    PHOTO       bigint,
    VERSION     INT         NOT NULL             DEFAULT 0
);
CREATE UNIQUE INDEX singer_unique_firstname_lastname_idx on SINGER(FIRST_NAME, LAST_NAME)

